### ISSUE TITLE
Material: EyeL and EyeR not having Alpha 

### ISSUE THREAD

**Issue by puli2004** [ScanMountGoat/Smush-Material-Research#14]
So I have been doing my Minecraft skin for a while and wanted Final Smash in the body fully. But the problem is that alpha is not getting into the textures and its only on the EyeL and EyeR. CrossArc does not see this. Only in-game does.

**Comment by ScanMountGoat** [comment]
It sounds like you're having issues with Cross Mod looking different than in game. That isn't really on topic for this repository, so I would appreciate it if you opened a new Cross Mod issue here: https://github.com/Ploaj/SSBHLib/issues
