### ISSUE TITLE
Material Parameters Mistake

### ISSUE THREAD

**Issue by zrksyd** [ScanMountGoat/Smush-Material-Research#27]
I noticed that the Material Parameters page says that BlendState's Unk6 can be 2 but according to the database file in Value Dumps, the only valid values are 0, 1, and 6.
![image](https://user-images.githubusercontent.com/6856627/193919047-d3d4a799-cff4-49c6-8eb9-1ce45dc7b0e3.png)

**Comment by ScanMountGoat** [comment]
There are valid values that are supported in game but not used for any models for some parameters like blend factors. I've never seen any noticeable changes from changing the other blend state values like Unk6 even at the graphics API level. It's unlikely this will be cleared up any time soon.

**Comment by zrksyd** [comment]
How do you know Unk6 = 2 is valid then?

**Comment by ScanMountGoat** [comment]
That's the problem. You can't. I must have tested all these values at some point and then decided it wasn't worth looking into more. It's not exposed in any of the APIs other than ssbh_lib_json, so it's not a big priority at the moment.
